# Generated by Django 4.2.2 on 2023-08-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesApi', '0002_notebook_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='notesApi.notebook'),
            preserve_default=False,
        ),
    ]
